version: '3'
services:
  #
  # indy node
  #
  indy-node:
    image: indy-node-base
    command: 'bash -c ''./start_node.sh'''
    networks:
      - redwit
    ports:
      - "${INDY_NODE_PORT}:${INDY_NODE_PORT}"
      - "${INDY_CLIENT_PORT}:${INDY_CLIENT_PORT}"
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - NODE_NUM=${NODE_NUM}
      - NODE_SEED=${NODE_SEED}
      - NODE_NAME=${NODE_NAME}
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
      - NETWORK_NAME=${NETWORK_NAME}
    volumes:
      - node-data:/home/indy/ledger
networks:
  redwit:

volumes:
  node-data:
